// src/app/layout.tsx

import type { Metadata, Viewport } from 'next';
import './globals.css';
// 👈 Импортируем наш клиентский компонент-обертку
import SessionWrapper from '../components/SessionWrapper';
import { chetty, stengazeta } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chetty.variable} ${stengazeta.variable} antialiased`}>
        {/* 👈 Оборачиваем здесь: SessionProvider теперь доступен для всех дочерних элементов */}
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
